project:
  type: book


book:
  date: "5/14/2025"
  search: true
  page-footer: "Copyright 2025"
  site-url: https://personalscience.com/vns/
  downloads: [pdf, epub, docx]
  cover-image: _resources/book/book-vns-kindle-cover-6x9 Medium.jpeg
  

bibliography: _resources/book/vns.bib
nocite: '@*'

format:
  html:
    theme: cosmo
    css: _resources/css/normalize.css
    standalone: true
    toc: true
    toc-depth: 2  
    link-external-newwindow: true
    execute:
      fig-format: svg
  pdf:
    toc: true
    documentclass: scrbook
    geometry: paperwidth=6in,paperheight=9in
    keep-tex: true
    toc-depth: 2  
    header-includes:
      - \raggedbottom
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
    standalone: true
    execute:
      fig-format: pdf
  docx:
    reference-doc: _resources/book/reference.docx

  epub:
    cover-image: _resources/book/book-vns-kindle-cover-6x9 Medium.jpeg